"""add patient medical_conditions

Revision ID: 087b19108e25
Revises: 6e9e0504269c
Create Date: 2026-08-05 15:38:00.517837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '087b19108e25'
down_revision: Union[str, Sequence[str], None] = '6e9e0504269c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows with an empty array; dropped
    # right after since new rows always send an explicit value from the API.
    op.add_column(
        'patients',
        sa.Column('medical_conditions', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.alter_column('patients', 'medical_conditions', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'medical_conditions')
    # ### end Alembic commands ###
