"""add consultation updated_at

Revision ID: 0d359f18e075
Revises: ffd4b73dcc26
Create Date: 2026-08-14 17:33:10.230294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d359f18e075'
down_revision: Union[str, Sequence[str], None] = 'ffd4b73dcc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'updated_at')
    # ### end Alembic commands ###
