"""add patient_payments - one combined bill per patient

Revision ID: 34e9425cb4bb
Revises: c7e7d5164f27
Create Date: 2026-08-24 14:25:32.781830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '34e9425cb4bb'
down_revision: Union[str, Sequence[str], None] = 'c7e7d5164f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # create_type=False: the payment_mode enum type already exists (used by
    # consultations/treatments/invoices/treatment_payments) — without this,
    # Postgres errors trying to CREATE TYPE a second time.
    op.create_table('patient_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', postgresql.ENUM('cash', 'card', 'upi', name='payment_mode', create_type=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_payments')
    # ### end Alembic commands ###
