"""add discount to consultations

Revision ID: 4e63788aef51
Revises: 34e9425cb4bb
Create Date: 2026-08-24 15:01:25.031436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e63788aef51'
down_revision: Union[str, Sequence[str], None] = '34e9425cb4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('discount_type', sa.String(length=10), nullable=True))
    op.add_column('consultations', sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'discount_value')
    op.drop_column('consultations', 'discount_type')
    # ### end Alembic commands ###
