"""add prescription diagnosis advice next_visit fields

Revision ID: 6e9e0504269c
Revises: ded91ea68a72
Create Date: 2026-08-05 14:34:35.475522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9e0504269c'
down_revision: Union[str, Sequence[str], None] = 'ded91ea68a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_entries', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('prescription_entries', sa.Column('advice', sa.Text(), nullable=True))
    op.add_column('prescription_entries', sa.Column('next_visit', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription_entries', 'next_visit')
    op.drop_column('prescription_entries', 'advice')
    op.drop_column('prescription_entries', 'diagnosis')
    # ### end Alembic commands ###
