"""add invoice number

Revision ID: 8defe9dafa8e
Revises: f5edd9a5c35f
Create Date: 2026-08-26 15:04:34.537882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8defe9dafa8e'
down_revision: Union[str, Sequence[str], None] = 'f5edd9a5c35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_number', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'invoice_number')
    # ### end Alembic commands ###
