"""dob nullable, add birth_year

Revision ID: c5fb7f5e4acc
Revises: 087b19108e25
Create Date: 2026-08-11 12:29:01.681724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fb7f5e4acc'
down_revision: Union[str, Sequence[str], None] = '087b19108e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('patients', 'birth_year')
    # ### end Alembic commands ###
