"""add invoice discount type and value

Revision ID: d0222574c950
Revises: c5fb7f5e4acc
Create Date: 2026-08-11 15:14:13.263135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0222574c950'
down_revision: Union[str, Sequence[str], None] = 'c5fb7f5e4acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('discount_type', sa.String(length=10), nullable=True))
    op.add_column('invoices', sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount_value')
    op.drop_column('invoices', 'discount_type')
    # ### end Alembic commands ###
