"""add patient_number

Revision ID: ded91ea68a72
Revises: 669bf0a52c1a
Create Date: 2026-08-05 12:52:22.365055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded91ea68a72'
down_revision: Union[str, Sequence[str], None] = '669bf0a52c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('patient_number', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint(None, 'patients', ['patient_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'patient_number')
    # ### end Alembic commands ###
