"""billing tracking - consultation paid_at, treatment discount, treatment payments

Revision ID: eec0f2b686c4
Revises: 0d359f18e075
Create Date: 2026-08-17 12:22:10.946878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'eec0f2b686c4'
down_revision: Union[str, Sequence[str], None] = '0d359f18e075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False: the payment_mode enum type already exists (used by
    # visits/consultations/invoices) — without this, Postgres errors trying
    # to CREATE TYPE a second time.
    op.create_table('treatment_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('treatment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', postgresql.ENUM('cash', 'card', 'upi', name='payment_mode', create_type=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consultations', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('treatments', sa.Column('discount_type', sa.String(length=10), nullable=True))
    op.add_column('treatments', sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('visits', 'listed_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'listed_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('treatments', 'discount_value')
    op.drop_column('treatments', 'discount_type')
    op.drop_column('consultations', 'paid_at')
    op.drop_table('treatment_payments')
    # ### end Alembic commands ###
