"""add staff registration_no

Revision ID: f5edd9a5c35f
Revises: 5992c9cfd7bd
Create Date: 2026-08-26 10:20:28.210145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5edd9a5c35f'
down_revision: Union[str, Sequence[str], None] = '5992c9cfd7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('registration_no', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'registration_no')
    # ### end Alembic commands ###
